// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- generated only after the OpenNext build.
// @ts-ignore Generated by `opennextjs-cloudflare build` before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";

import { handleCloudflareRequest } from "./src/cloudflare/admin-unavailable";

const worker = {
  fetch(request: Request, env: unknown, context: unknown) {
    return handleCloudflareRequest(openNextWorker.fetch, request, env, context);
  },
};

export default worker;
