import type { Locale } from "@/i18n/config";

export type PublicBookingCopy = typeof copy.en;

const copy = {
  bg: {
    title: "Запазване на час",
    intro: "Изберете масаж, продължителност и свободен час.",
    back: "Назад",
    continue: "Продължи",
    loading: "Зареждаме свободните часове...",
    unavailableTitle: "Онлайн записването временно не е достъпно",
    unavailableText: "Можете да продължите към Studio24.",
    retry: "Опитайте отново",
    steps: ["Услуга", "Вариант", "Дата и час", "Контакти", "Потвърждение"],
    serviceTitle: "Изберете услуга",
    serviceHint: "Ще покажем само вариантите и часовете за избрания масаж.",
    variantTitle: "Изберете продължителност",
    variantHint: "Цената и продължителността са окончателни за този избор.",
    minutes: "мин",
    scheduleTitle: "Изберете дата и час",
    scheduleHint: "Часовете се показват едва след избор на дата.",
    monthNavigation: "Навигация по месеци",
    previousMonth: "Предишен месец",
    nextMonth: "Следващ месец",
    availability: { available: "Свободно", limited: "Ограничено", unavailable: "Няма часове" },
    timesTitle: "Свободни часове",
    chooseDate: "Първо изберете дата",
    chooseTime: "Изберете час",
    noTimes: "За тази дата вече няма свободни часове.",
    loadingAvailability: "Проверяваме наличността...",
    availabilityError: "Не успяхме да заредим свободните часове. Опитайте отново.",
    loadingHold: "Задържаме часа...",
    holdError: "Не успяхме да задържим този час. Изберете друг.",
    conflict: "Този час току-що беше зает. Изберете друг свободен час.",
    holdLabel: "Часът е задържан за",
    holdExpired: "Задържането изтече. Изберете часа отново.",
    detailsTitle: "Вашите контакти",
    detailsHint: "Ще използваме данните само във връзка със записването.",
    name: "Име",
    phone: "Телефон",
    email: "Имейл (по желание)",
    contactPreference: "Предпочитан начин за контакт",
    preferences: { phone: "Телефон", viber: "Viber", telegram: "Telegram", email: "Имейл" },
    privacyPrefix: "Съгласен/на съм с",
    privacyLink: "политиката за поверителност",
    required: "Попълнете това поле.",
    invalidName: "Въведете име с поне 2 знака.",
    invalidPhone: "Въведете валиден телефон с 7 до 15 цифри.",
    invalidEmail: "Въведете валиден имейл адрес.",
    emailPreference: "Добавете имейл, за да изберете контакт по имейл.",
    reviewTitle: "Проверете записването",
    reviewHint: "Потвърждението създава записването веднага.",
    confirm: "Потвърди записването",
    confirming: "Потвърждаваме...",
    confirmError: "Не успяхме да потвърдим часа. Изберете свободен час отново.",
    summaryTitle: "Вашето записване",
    service: "Услуга",
    duration: "Продължителност",
    date: "Дата",
    time: "Час",
    contact: "Контакт",
    notSelected: "Не е избрано",
    successTitle: "Записването е потвърдено",
    successText: "Вашият час е запазен.",
    reference: "Референция",
    referenceUnavailable: "Налична в потвърждението",
  },
  ru: {
    title: "Запись на массаж",
    intro: "Выберите массаж, продолжительность и свободное время.",
    back: "Назад",
    continue: "Продолжить",
    loading: "Загружаем свободное время...",
    unavailableTitle: "Онлайн-запись временно недоступна",
    unavailableText: "Вы можете продолжить запись в Studio24.",
    retry: "Попробовать снова",
    steps: ["Услуга", "Вариант", "Дата и время", "Контакты", "Подтверждение"],
    serviceTitle: "Выберите услугу",
    serviceHint: "Мы покажем варианты и время только для выбранного массажа.",
    variantTitle: "Выберите продолжительность",
    variantHint: "Цена и продолжительность зафиксированы для этого варианта.",
    minutes: "мин",
    scheduleTitle: "Выберите дату и время",
    scheduleHint: "Точное время появится только после выбора даты.",
    monthNavigation: "Навигация по месяцам",
    previousMonth: "Предыдущий месяц",
    nextMonth: "Следующий месяц",
    availability: { available: "Свободно", limited: "Мало мест", unavailable: "Нет времени" },
    timesTitle: "Свободное время",
    chooseDate: "Сначала выберите дату",
    chooseTime: "Выберите время",
    noTimes: "На эту дату свободного времени больше нет.",
    loadingAvailability: "Проверяем доступность...",
    availabilityError: "Не удалось загрузить свободное время. Попробуйте ещё раз.",
    loadingHold: "Удерживаем время...",
    holdError: "Не удалось удержать это время. Выберите другое.",
    conflict: "Это время только что заняли. Выберите другое свободное время.",
    holdLabel: "Время удерживается ещё",
    holdExpired: "Время удержания истекло. Выберите время снова.",
    detailsTitle: "Ваши контакты",
    detailsHint: "Мы используем данные только для этой записи.",
    name: "Имя",
    phone: "Телефон",
    email: "Email (необязательно)",
    contactPreference: "Предпочтительный способ связи",
    preferences: { phone: "Телефон", viber: "Viber", telegram: "Telegram", email: "Email" },
    privacyPrefix: "Я принимаю",
    privacyLink: "политику конфиденциальности",
    required: "Заполните это поле.",
    invalidName: "Введите имя длиной не менее 2 символов.",
    invalidPhone: "Введите корректный телефон из 7-15 цифр.",
    invalidEmail: "Введите корректный email.",
    emailPreference: "Добавьте email, чтобы выбрать связь по email.",
    reviewTitle: "Проверьте запись",
    reviewHint: "После подтверждения запись будет создана сразу.",
    confirm: "Подтвердить запись",
    confirming: "Подтверждаем...",
    confirmError: "Не удалось подтвердить запись. Выберите свободное время снова.",
    summaryTitle: "Ваша запись",
    service: "Услуга",
    duration: "Продолжительность",
    date: "Дата",
    time: "Время",
    contact: "Контакт",
    notSelected: "Не выбрано",
    successTitle: "Запись подтверждена",
    successText: "Выбранное время закреплено за вами.",
    reference: "Номер записи",
    referenceUnavailable: "Указан в подтверждении",
  },
  ua: {
    title: "Запис на масаж",
    intro: "Оберіть масаж, тривалість і вільний час.",
    back: "Назад",
    continue: "Продовжити",
    loading: "Завантажуємо вільний час...",
    unavailableTitle: "Онлайн-запис тимчасово недоступний",
    unavailableText: "Ви можете продовжити запис у Studio24.",
    retry: "Спробувати знову",
    steps: ["Послуга", "Варіант", "Дата й час", "Контакти", "Підтвердження"],
    serviceTitle: "Оберіть послугу",
    serviceHint: "Ми покажемо варіанти й час лише для обраного масажу.",
    variantTitle: "Оберіть тривалість",
    variantHint: "Ціна та тривалість зафіксовані для цього варіанта.",
    minutes: "хв",
    scheduleTitle: "Оберіть дату й час",
    scheduleHint: "Точний час з'явиться лише після вибору дати.",
    monthNavigation: "Навігація за місяцями",
    previousMonth: "Попередній місяць",
    nextMonth: "Наступний місяць",
    availability: { available: "Вільно", limited: "Мало місць", unavailable: "Немає часу" },
    timesTitle: "Вільний час",
    chooseDate: "Спочатку оберіть дату",
    chooseTime: "Оберіть час",
    noTimes: "На цю дату вільного часу більше немає.",
    loadingAvailability: "Перевіряємо доступність...",
    availabilityError: "Не вдалося завантажити вільний час. Спробуйте ще раз.",
    loadingHold: "Утримуємо час...",
    holdError: "Не вдалося утримати цей час. Оберіть інший.",
    conflict: "Цей час щойно зайняли. Оберіть інший вільний час.",
    holdLabel: "Час утримується ще",
    holdExpired: "Час утримання минув. Оберіть час знову.",
    detailsTitle: "Ваші контакти",
    detailsHint: "Ми використаємо дані лише для цього запису.",
    name: "Ім'я",
    phone: "Телефон",
    email: "Email (необов'язково)",
    contactPreference: "Бажаний спосіб зв'язку",
    preferences: { phone: "Телефон", viber: "Viber", telegram: "Telegram", email: "Email" },
    privacyPrefix: "Я приймаю",
    privacyLink: "політику конфіденційності",
    required: "Заповніть це поле.",
    invalidName: "Введіть ім'я щонайменше з 2 символів.",
    invalidPhone: "Введіть коректний телефон із 7-15 цифр.",
    invalidEmail: "Введіть коректний email.",
    emailPreference: "Додайте email, щоб обрати зв'язок через email.",
    reviewTitle: "Перевірте запис",
    reviewHint: "Після підтвердження запис буде створено одразу.",
    confirm: "Підтвердити запис",
    confirming: "Підтверджуємо...",
    confirmError: "Не вдалося підтвердити запис. Оберіть вільний час знову.",
    summaryTitle: "Ваш запис",
    service: "Послуга",
    duration: "Тривалість",
    date: "Дата",
    time: "Час",
    contact: "Контакт",
    notSelected: "Не обрано",
    successTitle: "Запис підтверджено",
    successText: "Обраний час закріплено за вами.",
    reference: "Номер запису",
    referenceUnavailable: "Зазначено в підтвердженні",
  },
  en: {
    title: "Book an appointment",
    intro: "Choose a massage, duration and available time.",
    back: "Back",
    continue: "Continue",
    loading: "Loading available times...",
    unavailableTitle: "Online booking is temporarily unavailable",
    unavailableText: "You can continue your booking in Studio24.",
    retry: "Try again",
    steps: ["Service", "Option", "Date and time", "Contact", "Confirm"],
    serviceTitle: "Choose a service",
    serviceHint: "We will show options and times only for the selected massage.",
    variantTitle: "Choose a duration",
    variantHint: "The price and duration are fixed for this option.",
    minutes: "min",
    scheduleTitle: "Choose a date and time",
    scheduleHint: "Exact times appear only after you choose a date.",
    monthNavigation: "Calendar month navigation",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    availability: { available: "Available", limited: "Limited", unavailable: "Unavailable" },
    timesTitle: "Available times",
    chooseDate: "Choose a date first",
    chooseTime: "Choose a time",
    noTimes: "There are no remaining times on this date.",
    loadingAvailability: "Checking availability...",
    availabilityError: "We could not load available times. Try again.",
    loadingHold: "Holding your time...",
    holdError: "We could not hold this time. Choose another one.",
    conflict: "This time was just taken. Choose another available time.",
    holdLabel: "Time held for",
    holdExpired: "The hold expired. Choose your time again.",
    detailsTitle: "Your contact details",
    detailsHint: "We will use these details only for this booking.",
    name: "Name",
    phone: "Phone",
    email: "Email (optional)",
    contactPreference: "Preferred contact method",
    preferences: { phone: "Phone", viber: "Viber", telegram: "Telegram", email: "Email" },
    privacyPrefix: "I agree to the",
    privacyLink: "privacy policy",
    required: "Complete this field.",
    invalidName: "Enter a name with at least 2 characters.",
    invalidPhone: "Enter a valid phone number with 7-15 digits.",
    invalidEmail: "Enter a valid email address.",
    emailPreference: "Add an email address to choose email contact.",
    reviewTitle: "Review your booking",
    reviewHint: "Confirming creates the appointment immediately.",
    confirm: "Confirm booking",
    confirming: "Confirming...",
    confirmError: "We could not confirm the appointment. Choose an available time again.",
    summaryTitle: "Your booking",
    service: "Service",
    duration: "Duration",
    date: "Date",
    time: "Time",
    contact: "Contact",
    notSelected: "Not selected",
    successTitle: "Booking confirmed",
    successText: "Your selected time is secured.",
    reference: "Booking reference",
    referenceUnavailable: "Included in the confirmation",
  },
} as const satisfies Record<Locale, Record<string, unknown>>;

export function getPublicBookingCopy(locale: Locale): PublicBookingCopy {
  return copy[locale] as PublicBookingCopy;
}
